export const TEXT = {
  APP_NAME: "FLYBUY",
  APP_TAGLINE: "Your one-stop shop",

  NAV_HOME: "Home",
  NAV_PRODUCTS: "Products",
  NAV_CART: "Cart",
  NAV_ADD_PRODUCT: "Add Product",

  BTN_ADD_TO_CART: "Add to Cart",
  BTN_SAVE_CART: "Save Cart",
  BTN_PROCEED_CHECKOUT: "Proceed to Checkout",
  BTN_CONTINUE_SHOPPING: "Continue Shopping",
  BTN_CLEAR_CART: "Clear Cart",
  BTN_REMOVE: "Remove",
  BTN_EDIT: "Edit",
  BTN_DELETE: "Delete",
  BTN_SAVE: "Save",
  BTN_UPDATE: "Update",
  BTN_CANCEL: "Cancel",
  BTN_SUBMIT: "Submit",
  BTN_BACK: "Back to Home",
  BTN_YES_DELETE: "Yes, Delete",
  BTN_VIEW_DETAILS: "View Details",

  FORM_TITLE_LABEL: "Product Title",
  FORM_PRICE_LABEL: "Price",
  FORM_CATEGORY_LABEL: "Category",
  FORM_DESCRIPTION_LABEL: "Description",
  FORM_IMAGE_LABEL: "Image URL",
  FORM_TITLE_PLACEHOLDER: "Enter product title",
  FORM_PRICE_PLACEHOLDER: "Enter price",
  FORM_CATEGORY_PLACEHOLDER: "Enter category",
  FORM_DESCRIPTION_PLACEHOLDER: "Enter description",
  FORM_IMAGE_PLACEHOLDER: "Enter image URL",

  PAGE_ADD_PRODUCT: "Add New Product",
  PAGE_EDIT_PRODUCT: "Edit Product",
  PAGE_PRODUCT_DETAILS: "Product Details",
  PAGE_SHOPPING_CART: "Shopping Cart",
  PAGE_PRODUCTS: "Products",

  CART_EMPTY: "Your Cart is Empty",
  CART_ITEM_ADDED: "Item added to cart successfully!",
  CART_ITEM_REMOVED: "Item removed from cart",
  CART_CLEARED: "Cart cleared successfully",
  CART_SAVED: "Cart saved successfully!",
  CART_ITEMS_COUNT: "items",
  CART_TOTAL: "Total",
  CART_SUBTOTAL: "Subtotal",
  CART_SHIPPING: "Shipping",
  CART_FREE_SHIPPING: "FREE",

  PRODUCT_ADDED: "Product added successfully!",
  PRODUCT_UPDATED: "Product updated successfully!",
  PRODUCT_DELETED: "Product deleted successfully!",
  PRODUCT_DELETE_CONFIRM: "Really want to delete this product?",
  PRODUCT_NOT_FOUND: "Product not found",

  SEARCH_PLACEHOLDER: "Search products...",
  FILTER_CATEGORY: "Filter by Category",
  FILTER_ALL_CATEGORIES: "All Categories",
  SORT_BY: "Sort by",
  SORT_PRICE_LOW_HIGH: "Price: Low to High",
  SORT_PRICE_HIGH_LOW: "Price: High to Low",
  SORT_NAME_A_Z: "Name: A to Z",
  SORT_NAME_Z_A: "Name: Z to A",

  LOADING: "Loading...",
  LOADING_PRODUCTS: "Loading products...",
  LOADING_CART: "Loading cart...",
  ERROR_OCCURRED: "An error occurred",
  ERROR_LOADING_PRODUCTS: "Error loading products",
  ERROR_LOADING_CART: "Error loading cart",
  ERROR_NETWORK: "Network error. Please try again.",

  VALIDATION_REQUIRED: "This field is required",
  VALIDATION_PRICE_POSITIVE: "Price must be a positive number",
  VALIDATION_PRICE_REQUIRED: "Price is required",
  VALIDATION_TITLE_REQUIRED: "Title is required",
  VALIDATION_CATEGORY_REQUIRED: "Category is required",
  VALIDATION_DESCRIPTION_REQUIRED: "Description is required",
  VALIDATION_IMAGE_INVALID: "Please enter a valid image URL",

  PAGINATION_PREV: "Previous",
  PAGINATION_NEXT: "Next",
  PAGINATION_PAGE: "Page",
  PAGINATION_OF: "of",
  PAGINATION_SHOWING: "Showing",

  CURRENCY: "₹",
  CATEGORY: "Category",
  PRICE: "Price",
  QUANTITY: "Quantity",
  ORDER_SUMMARY: "Order Summary",
  NO_RESULTS: "No products found",
  TRY_DIFFERENT_SEARCH: "Try a different search term"
};

export default TEXT;